stages:
  - tag

tag_version:
  stage: tag
  only:
    changes:
      - version.txt
  before_script:
    - VERSION=$(cat version.txt | tr -d '[:space:]')
    - |-
      if echo "$VERSION" | grep -q "dev"; then
        echo "Version contains 'dev', skipping tagging and pushing."
        exit 0
      fi
  script:
    - |-
      if ! git rev-parse "v$VERSION" >/dev/null 2>&1; then
        git tag -a "v$VERSION" -m "Automatic release version $VERSION"
      fi
    - REPO_URL=$(echo $CI_PROJECT_URL | sed "s|https://|https://git:$GITLAB_ACCESS_TOKEN@|").git
    - git push "$REPO_URL" "v$VERSION"
  environment:
    name: production
