stages:
  - deploy

deploy:
  stage: deploy
  only:
    changes:
      - version.txt
  before_script:
    - |-
      if [ ! -f version.txt ]; then
        echo "version.txt file not found, skipping deploy."
        exit 0
      fi
    - VERSION=$(<version.txt tr -d '[:space:]')
    - |-
      if echo "$VERSION" | grep -q "dev"; then
        echo "Version contains 'dev', skipping deploy."
        exit 0
      fi
  script:
    # tag
    - |-
      if ! git rev-parse "v$VERSION" >/dev/null 2>&1; then
        git tag -a "v$VERSION" -m "Automatic release version $VERSION"
      fi
    - REPO_URL=$(echo $CI_PROJECT_URL | sed "s|https://|https://git:$GITLAB_ACCESS_TOKEN@|").git
    - git push "$REPO_URL" "v$VERSION"
    # pipy
    - pip3 install twine
    - rm -rf dist/
    - python3 setup.py sdist build
    - python3 -m twine upload dist/* -u __token__ -p $PYPI_ACCESS_TOKEN --skip-existing
    # github
    - URL=$(<url.txt tr -d '[:space:]')
    - REPO_URL=$(echo $URL | sed "s|https://|https://git:$GITHUB_ACCESS_TOKEN@|").git
    - git push "$REPO_URL" HEAD:refs/heads/$CI_COMMIT_BRANCH
    - git push "$REPO_URL" "v$VERSION"
  environment:
    name: production
